# golangci-lint configuration
version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Checking for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple and stylecheck)
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - goconst       # Finds repeated strings that could be constants
    - gocyclo       # Computes cyclomatic complexity

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    
    # Exclude known linters from being run on examples
    - path: examples/
      linters:
        - errcheck
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
